# Generated by Django 3.1.4 on 2020-12-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_profile', '0002_auto_20201205_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofle',
            name='f_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofle',
            name='l_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofle',
            name='phone_number',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
