# Generated by Django 3.1.4 on 2020-12-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_profile', '0003_auto_20201205_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofle',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
