# Generated by Django 3.1.4 on 2020-12-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_profile', '0005_auto_20201205_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofle',
            name='active_code',
            field=models.IntegerField(null=True),
        ),
    ]
